### ISSUE TITLE
Exporting nfbLab xml

### ISSUE THREAD

**Issue by andreasxp** [bioelectric-interfaces/nfb#44]
*Originally opened by @VladislavAksiotis at `andreasxp/nfb`.*

When I imported the xml file from nfb lab and then exported it from studio as a new file, I found that some values have changed:
fFFTWindowSize (was 500, became 1000)
sTemporalFilterType (was cfir, became butter)

**Comment by VladislavAksiotis** [comment]
I believe this issue could be closed because it was resolved in the studio repository.
