### ISSUE TITLE
SSD band implements with width -1

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb#50]
When change the bandwidth in the SSD, the real filtering is implemented with the width with -1 (for example, we give 8 and 12 boundaries, but the data is processing with 7 and 11).

**Comment by nikolaims** [comment]
Solved by hotfix commit:
https://github.com/bioelectric-interfaces/nfb/commit/13d0c662155ee689895f77b4d0ab84039d2b6cb7
