### ISSUE TITLE
Endless protocol without the subject window 

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb#56]
I created an experiment where I don't need the subject window and unchecked this box in the settings. The baseline block was supposed to last 10 seconds and 5000 samples, but it lasts longer than that. Notably, with subject window everything is alright.
![new](https://user-images.githubusercontent.com/60115817/114323553-675ed080-9b2e-11eb-8cff-f68f03eeb838.jpg)

**Comment by andreasxp** [comment]
Implemented in 0.2 by removing the "Show subject window" option. Subject window can be manually hidden by minimizing it.
