### ISSUE TITLE
Detection task and extra message

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb#63]
In the protocol window, the "Enable detection task" and "Add half time extra message (for CSP)" checkboxes are deprecated  features, so they should be removed.

**Comment by andreasxp** [comment]
For half-time extra message, does this imply that both the checkbox and the message field are to be removed?

**Comment by VladislavAksiotis** [comment]
> For half-time extra message, does this imply that both the checkbox and the message field are to be removed?

Yes, both, the checkbox and the message field was used for the previous version.

**Comment by andreasxp** [comment]
Forgot to mention in the commit message, but this is implemented in 0.2 in f58639a.
